//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class main
    {
        public int id { get; set; }
        public string na { get; set; }
        public Nullable<int> wi { get; set; }
    }
}
